CREATE TABLE burgers (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    burger_name VARCHAR(60) NOT NULL,
    devoured BOOLEAN
);

INSERT * INTO burgers (burger_name);
VALUES 
("HAMBURGER");
("CHEESEBURGER");
("BACON CHEESBURGER");
("EGG CHEESEBURGER");
("BACON EGG CHEESEBURGER");